import Head from 'next/head'

export default function Home(initialData) {

  const handleInputChange = (e) => {

  }

  const search = (e) => {
    e.preventDefault();
  }

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Giphy search app</h1>

      <form onSubmit={search}>
        <input name='searchTerm' type='text' onChange={handleInputChange}/>
        <input type='submit' value='Search'/>
      </form>

      <div className='giphy-search-results-grid'>
      {initialData.gifs.data.map((gif, index) => {
          return (
          <figure key={index}>
            <figcaption>{gif.title}</figcaption>
            <img src={gif.images.original.url} alt={gif.title}></img>
          </figure>);
        })}
      </div>
    </div>
  )
}

export async function getStaticProps() {
  const apiResponse = await fetch('https://api.giphy.com/v1/gifs/search?q=nature&api_key=RHZN27idONbQeH1U8T7IVQm7LWk5Jcsk&limit=20')
  const jsoned = await apiResponse.json()
  return { props: { gifs: jsoned }}
}
